version: '3'
services:
  web:
    build:
      dockerfile:  ./docker/Dockerfile.web
      context: .
    image: vitorp/rails
    container_name: grade-web-api
    ports:
      - "3000:3000"
    networks:
      - grade-web-api-network
    depends_on:
      - db
    volumes:
      - ".:/webapp"
    entrypoint: /bin/sh lib/docker-entrypoint-dev.sh
  db:
    image: postgres:latest
    container_name: meu-postgres
    volumes:
      - "./db-data:/var/lib/postgresql/data"
    networks:
      - grade-web-api-network
networks:
  grade-web-api-network:
    driver: bridge
